#include "Enclave_t.h" // Headers for trusted part (autogenerated by edger8r)
#include "sgx_trts.h"
#include "sqlite3.h"
#include <string>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

sqlite3* db; // Database connection object

// SQLite callback function for printing results
static int callback(void *NotUsed, int argc, char **argv, char **azColName){
    int i;
    for(i = 0; i < argc; i++){
        std::string azColName_str = azColName[i];
        std::string argv_str = (argv[i] ? argv[i] : "NULL");
        ocall_print_string((azColName_str + " = " + argv_str + "\n").c_str());
    }
    ocall_print_string("\n");
    return 0;
}

void ecall_opendb(const char *dbname){
    if (db != NULL) {
        sqlite3_close(db);
        db = NULL;
    }
    
    // Ensure dbname is not null
    if (dbname == NULL) {
        return;
    }
    
    size_t len = strlen(dbname);
    // Check if dbname is within enclave memory
    if (!sgx_is_within_enclave(dbname, len + 1)) {
        return;
    }

    // Copy to local buffer to avoid potential TOCTOU or bad pointer issues
    char *dbname_buf = (char *)malloc(len + 1);
    if (dbname_buf == NULL) {
        return;
    }
    memcpy(dbname_buf, dbname, len + 1);

    int rc; // For return status of SQLite
    rc = sqlite3_open(dbname_buf, &db); // Opening database

    if (rc) {
        ocall_println_string("SQLite error - can't open database connection: ");
        ocall_println_string(sqlite3_errmsg(db));
        sqlite3_close(db);
        db = NULL;
        free(dbname_buf);
        return;
    }
    ocall_print_string("Enclave: Created database connection to ");
    ocall_println_string(dbname_buf);
    free(dbname_buf);
}

void ecall_execute_sql(const char *sql){
    if (db == NULL) {
        ocall_println_string("Error: Database not open");
        return;
    }
    
    if (sql == NULL) return;

    size_t len = strlen(sql);
    if (!sgx_is_within_enclave(sql, len + 1)) return;

    char *sql_buf = (char *)malloc(len + 1);
    if (sql_buf == NULL) return;
    memcpy(sql_buf, sql, len + 1);

    int rc;
    char *zErrMsg = 0;
    rc = sqlite3_exec(db, sql_buf, callback, 0, &zErrMsg);
    if (rc) {
        ocall_print_string("SQLite error: ");
        ocall_println_string(sqlite3_errmsg(db));
        if (zErrMsg) sqlite3_free(zErrMsg);
    }
    free(sql_buf);
}

void ecall_closedb(){
    sqlite3_close(db);
    db = NULL;
    ocall_println_string("Enclave: Closed database connection");
}
